### ISSUE TITLE
Add Dyeable Feature 1.21

### ISSUE THREAD

**Issue by makumaku1974** [pnk2u/More-Bed-Variants#1]
A simple request since I tried dyeing my white bed to bed pink and the recipe change is more expensive.

**Comment by pnk2u** [comment]
Thanks for reporting, I added the dyeing recipes for all beds in version 1.2.0 that was just released. I hope that fixes your issue, let me know if it does or if there is something else.

**Comment by makumaku1974** [comment]
this is a great fix. More power to you
