### ISSUE TITLE
All Gray Bed variants missing in beds.json

### ISSUE THREAD

**Issue by TheMasterBlaster** [pnk2u/More-Bed-Variants#2]
None of the gray beds are in lieonstudio/tags/block/beds.json and lieonstudio/tags/item/beds.json
There are light gray beds but not gray beds

**Comment by pnk2u** [comment]
Oh, thanks for the report. Will fix asap, just wondering, did any bug occur related to this? ^^

**Comment by pnk2u** [comment]
Bug fix version 1.2.1 is up. (:

**Comment by TheMasterBlaster** [comment]
Not exactly a bug but I noticed it when using the [Where Is It](https://modrinth.com/mod/where-is-it) mod, and again when messing with the [Seamless](https://modrinth.com/mod/seamless) mod. But I really appreciate the quick fix! :D

**Comment by TheMasterBlaster** [comment]
Just updated on client and server, seems all good!
