### ISSUE TITLE
Villagers don't recognise the beds

### ISSUE THREAD

**Issue by BatJPJonyGod** [pnk2u/More-Bed-Variants#3]
The villagers don't assign to any of the beds other than the default oak beds and they don't sleep in them too.

**Comment by pnk2u** [comment]
Thanks for reporting this issue, I successfully managed to implement this missing property and will a release a 1.3.0 later today with that fix; once released I will comment here again.

**Comment by pnk2u** [comment]
Okay, the mentioned update (1.3.0) has now been released - let me know if that works on your end, too, and if there are any other issues. So that, if there's nothing else, I can close this issue. Thank you. (:

**Comment by BatJPJonyGod** [comment]
All ok, villagers sleep in the additionnal beds now. Thank you for the quick fix!
